- hosts: web[0] 
  tasks:
   
   - name: Reset Kubernetes component
     shell: "kubeadm reset --force"
     register: reset_cluster

   - name: remove etcd directory
     shell: "/bin/rm -rf /var/lib/etcd" 

   - name: Initialize the Kubernetes cluster using kubeadm
     command: kubeadm init --pod-network-cidr=10.244.0.0/16
     register: kubeadm
  
   - debug: msg={{ kubeadm.stdout_lines }}
 
   - name: Create kube directory
     file:
       path: /root/.kube
       state: directory

   - name: Copy kubeconfig to home
     copy:
       src:  /etc/kubernetes/admin.conf
       dest:  /root/.kube/config
       owner: root
       group: root
       mode: '0644'

   - name: Install networking plugin to kubernetes cluster
     command: kubectl apply -f {{ item}} 
     with_items:
     - https://raw.githubusercontent.com/coreos/flannel/62e44c867a2846fefb68bd5f178daf4da3095ccb/Documentation/kube-flannel.yml 
#     - https://docs.projectcalico.org/v3.5/getting-started/kubernetes/installation/hosted/etcd.yaml
#     - https://docs.projectcalico.org/v3.5/getting-started/kubernetes/installation/hosted/calico.yaml
     - https://raw.githubusercontent.com/kubernetes/dashboard/v1.10.1/src/deploy/recommended/kubernetes-dashboard.yaml
     - cluster-admin.yaml
   
   - name: Run KubeProxy
     shell: nohup kubectl proxy --address='0.0.0.0' --accept-hosts='^*$' </dev/null >/dev/null 2>&1 &
    
   - name: Generate join token
     shell: kubeadm token create --print-join-command
     register: kubeadm_join_cmd

   - set_fact:
       kubeadm_join: "{{ kubeadm_join_cmd.stdout }}"

   - debug: var=kubeadm_join

   - name: Store join command
     action: copy content="{{ kubeadm_join }}" dest="/etc/kubernetes/kubeadm-join.command"

- hosts: web[1]
  tasks:
   - name: Reset Kubernetes component
     shell: "kubeadm reset --force"
     register: reset_cluster
   
   - name: Create kube directory
     file:
       path: /etc/kubernetes
       state: directory

   - name: Copy kubeadm-join command to node
     copy:
       src: "/etc/kubernetes/kubeadm-join.command"
       dest: "/etc/kubernetes/kubeadm-join.command"

   - name: Install helm
     shell: kubectl apply -f helm/helm.yaml


- hosts: web[1]
  vars:
     kubeadm_join: "{{ lookup('file', '/etc/kubernetes/kubeadm-join.command') }}"
  tasks: 
   - name: Run kubeadm join
     shell: "{{ kubeadm_join }} --ignore-preflight-errors=swap"
     

