- hosts: master 
  tasks:
   
   - name: Reset Kubernetes component
     shell: "kubeadm reset --force"
     register: reset_cluster

   - name: remove etcd directory
     shell: "/bin/rm -rf /var/lib/etcd" 

   - name: Initialize the Kubernetes cluster using kubeadm
     command: kubeadm init --pod-network-cidr=10.244.0.0/16 --v 9
     register: kubeadm
  
   - debug: msg={{ kubeadm.stdout_lines }}
 
   - name: Create kube directory
     file:
       path: /root/.kube
       state: directory

   - name: Copy kubeconfig to home
     copy:
       src:  /etc/kubernetes/admin.conf
       dest:  /root/.kube/config
       owner: root
       group: root
       mode: '0644'

   - name: Install networking plugin to kubernetes cluster
     command: kubectl apply -f {{ item}} 
     with_items:
     - https://raw.githubusercontent.com/coreos/flannel/2140ac876ef134e0ed5af15c65e414cf26827915/Documentation/kube-flannel.yml 
#     - https://docs.projectcalico.org/v3.5/getting-started/kubernetes/installation/hosted/etcd.yaml
#     - https://docs.projectcalico.org/v3.5/getting-started/kubernetes/installation/hosted/calico.yaml

   - name: Install Kubernetes Dashboard
     command: kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v1.10.1/src/deploy/recommended/kubernetes-dashboard.yaml

   - name: Change permissions of the service account(kubernetes-dashboard) for the dashboard
     command: kubectl create clusterrolebinding kubernetes-dashboard -n kube-system --clusterrole=cluster-admin --serviceaccount=kube-system:kubernetes-dashboard

   - name: Deploy heapster to enable container cluster monitoring and performance analysis on your cluster
     command: kubectl apply -f https://raw.githubusercontent.com/kubernetes/heapster/master/deploy/kube-config/influxdb/heapster.yaml

   - name: Deploy the influxdb backend for heapster to your cluster
     command: kubectl apply -f https://raw.githubusercontent.com/kubernetes/heapster/master/deploy/kube-config/influxdb/influxdb.yaml

   - name: Create the heapster cluster role binding for the dashboard
     command: kubectl apply -f https://raw.githubusercontent.com/kubernetes/heapster/master/deploy/kube-config/rbac/heapster-rbac.yaml
 
   - name: Run KubeProxy
     shell: nohup kubectl proxy --address='0.0.0.0' --accept-hosts='^*$' </dev/null >/dev/null 2>&1 &
    
   - name: Generate join token
     shell: kubeadm token create --print-join-command
     register: kubeadm_join_cmd

   - set_fact:
       kubeadm_join: "{{ kubeadm_join_cmd.stdout }}"

   - debug: var=kubeadm_join

   - name: Store join command
     action: copy content="{{ kubeadm_join }}" dest="/etc/kubernetes/kubeadm-join.command"

- hosts: node
  tasks:
   - name: Reset Kubernetes component
     shell: "kubeadm reset --force"
     register: reset_cluster

   - debug: var=reset_cluster

   - name: Create kube directory
     file:
       path: /etc/kubernetes
       state: directory

   - name: Copy kubeadm-join command to node
     copy:
       src: "/etc/kubernetes/kubeadm-join.command"
       dest: "/etc/kubernetes/kubeadm-join.command"

- hosts: node
  vars:
     kubeadm_join: "{{ lookup('file', '/etc/kubernetes/kubeadm-join.command') }}"
  tasks:

   - name: Reset Kubernetes component
     shell: "kubeadm reset --force"
     register: reset_cluster

   - name: remove kubernetes directory
     shell: "/bin/rm -rf /etc/kubernetes" 

   - name: Run kubeadm join
     shell: "{{ kubeadm_join }} --ignore-preflight-errors=swap"
     
- hosts: master
  tasks:
   - name: Get Node name
     shell: "kubectl get nodes  | grep -v master | awk '{print $1}' | grep -v NAME"
     register: node_name

   - debug: var=node_name

   - name: Lable the node
     shell: "kubectl label node {{ item }} node-role.kubernetes.io/node="
     with_items: "{{ node_name.stdout_lines }}"  

   - name: Install helm
     shell: ansible-playbook -i inventory /root/kubernetes_vmware/helm/helm.yaml
     ignore_errors: true 
