    
---
- hosts: web[0]
  tasks:
   - name: "Create tmp directory"
     file:
       path: "/tmp"
       state: directory
       mode: 0755

   - name: "Check if Helm is installed"
     shell: command -v helm >/dev/null 2>&1
     register: helm_exists
     ignore_errors: yes

   - name: "Install Helm"
     block:
       - name: "Get Helm installer"
         get_url:
           url: https://raw.githubusercontent.com/helm/helm/master/scripts/get
           dest: "/tmp/get_helm.sh"
           mode: 0755
  
       - name: "Run the installer"
         shell: "/tmp/get_helm.sh"

     when: helm_exists.rc > 0

   - name: "RBAC configuration"
     shell: "kubectl apply -f helm/rbac-config.yaml"

   - name: "Init Helm"
     shell: "helm init --service-account tiller"

   - name: "Update Helm repo"
     shell: "helm repo update"

   - name: "Clean-up"
     file:
       path: "/tmp"
       state: absent
     ignore_errors: yes
